apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: password-token
  namespace: monitoring
spec:
  parameters:
    objects: |
      - objectName: "prodmyapppassword"
        objectType: "ssmparameter"
  provider: aws
  secretObjects:
    - data:
        - key: password_token
          objectName: password_token
      secretName: password-token
      type: Opaque